### ISSUE TITLE
page assets not loading

### ISSUE THREAD

**Issue by influx6** [dgryski/gophervids#24]
Assets links like the body pattern refuse to load, we need to fix that, i believe this is the same issue causing others not to load

**Comment by influx6** [comment]
![screenshot from 2015-04-05 22 01 31](https://cloud.githubusercontent.com/assets/131629/6998603/b3e528f6-dbdf-11e4-986a-473b7759d8f9.png)

**Comment by dgryski** [comment]
Asserts were 0 bytes due to failed merge.  Fixed.
