### ISSUE TITLE
Deleted Videos

### ISSUE THREAD

**Issue by 0xbzho** [dgryski/gophervids#41]
https://www.youtube.com/watch?v=S_NdzSj1syg - unavailable
https://www.youtube.com/watch?v=_QCQnxGxTBk - unavailable
https://www.youtube.com/watch?v=GjGRhIl0xWs - private
https://www.youtube.com/watch?v=iux7MBPUKZI - account terminated
https://www.youtube.com/watch?v=eTnosbpVC-g - unavailable
https://www.youtube.com/watch?v=YUigj99zXLU - account terminated
https://www.youtube.com/watch?v=9liuBycg3IA - unavailable
https://www.youtube.com/watch?v=USr0Bvg1ZOo - private
https://www.youtube.com/watch?v=vUqK-0PytV4 - unavailable
https://www.youtube.com/watch?v=61O6uMFzVtw - unavailable

**Comment by dgryski** [comment]
Thanks;  I'll go through the full list of videos and check their status.
